site_name: Mill
repo_url: https://github.com/CircuitCoder/mill
repo_name: CircuitCoder/mill
edit_uri: edit/master/doc/docs/

copyright: Copyright © Mill developers, released under CC BY-NC-SA 4.0

plugins:
  - search:
  - git-revision-date-localized:
      type: iso_datetime
      fallback_to_build_date: true
      locale: zh
      time_zone: Asia/Shanghai

theme:
  name: material
  language: zh
  palette:
    primary: blue grey
    accent: orange
  features:
    - navigation.tabs
    - navigation.instant
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides

nav:
  - 主页: index.md
  - 示例 CPU 设计:
    - 总览: arch/overview.md
    - 实现细节: arch/impl.md
    - 扩展开发指南: arch/ext.md
  - 测试框架:
    - Recipes: usage/recipes.md
    - riscv-tests: usage/riscv-tests.md
    - GTKWave / FST: usage/gtkwave.md
  - 开发日志:
    - 主页: timeline/index.md
    - "2020-10-03": timeline/2020-10-03.md
    - "2020-10-18": timeline/2020-10-18.md
    - "2020-10-21": timeline/2020-10-21.md
    - "2020-10-25": timeline/2020-10-25.md
    - "2020-10-26": timeline/2020-10-26.md

extra_css:
  - styles/index.css

markdown_extensions:
  - mdx_truly_sane_lists
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
